### ISSUE TITLE
集成pod后 配置完成 运行代码报错

### ISSUE THREAD

**Issue by hms040717007** [JmoVxia/CLPlayer#11]
<img width="1205" alt="default" src="https://user-images.githubusercontent.com/17900926/29461591-dc3731e4-845e-11e7-98b4-9a79e390438e.png">

**Comment by hms040717007** [comment]
代码是没有问题的

**Comment by hms040717007** [comment]
你好,集成pod会报这个错.播放器设置都是按照你demo代码设置的,集成完运行就报错

**Comment by yuying2012** [comment]
我的也是

**Comment by yuying2012** [comment]
![bb31a031-5ee1-4b76-a348-95f29f40bc77](https://user-images.githubusercontent.com/9688281/29556062-3ac510aa-8757-11e7-805d-6cc66ef27770.png)

**Comment by JmoVxia** [comment]
代码可以发我邮箱一份不  lin.chen@91ckd.com

**Comment by yuying2012** [comment]
完全按照demo的配置集成的.用的storyboard构建的界面.

**Comment by JmoVxia** [comment]
storyboard没有测试过，用的纯代码，是TabbarController下面直接UIViewController还是有导航控制器？

**Comment by yuying2012** [comment]
TabbarController页面中有导航栏控制器

**Comment by hms040717007** [comment]
我的是纯代码 也是会报错的

**Comment by JmoVxia** [comment]
能不能分离一个Demo给我看看，我测试没有遇到，具体情况我先看一下

**Comment by yuying2012** [comment]
我同时pod了'ZFPlayer'这个库就能运行了,应该是某个地方配置的问题.

**Comment by JmoVxia** [comment]
额，我去参考一下

**Comment by hms040717007** [comment]
和我的问题一样,我就是没说,因为很奇怪,集成两个就没事

**Comment by yuying2012** [comment]
但是同时pod之后,点击视频全屏按钮界面就乱了,,,,,,,

**Comment by JmoVxia** [comment]
pod updtae CLPlayer 更新1.1.0版本，看看还会不会崩溃

**Comment by yuying2012** [comment]
可以了,不崩溃了.感谢.可否加一个是否正在播放还是暂停的状态呢?想自己手动控制暂停,但是全屏下不知道用户是否播放还是暂停

**Comment by JmoVxia** [comment]
使用运行时在加载的时候动态替换系统方法，给了一个初始值，不然会出现无限大的数字，引起越界导致崩溃，播放状态稍等下，稍后我加上

**Comment by JmoVxia** [comment]
新增了是否真正播放接口，updtae新版本

**Comment by yuying2012** [comment]
好的,马上用,还发现了一个问题一会我截图发给你看下

**Comment by yuying2012** [comment]
![img_0945](https://user-images.githubusercontent.com/9688281/29559730-7b83b4e2-8762-11e7-8fac-db778390ccf8.PNG)
![img_0946](https://user-images.githubusercontent.com/9688281/29559734-7f1d92a8-8762-11e7-8d85-cb36e55f0b6b.PNG)
我自己定义了一个toolbar,视频比例不是全屏的时候,能显示,但是如果视频是全屏的比例,自己加的toolbar就会被覆盖,是否播放的时候,player层被顶置到最上层了呢?这样有什么好的解决办法呢?

**Comment by JmoVxia** [comment]
新版本已经使用Swift重构
