### ISSUE TITLE
全屏状态响应点击返回按钮的回调方法 界会错位

### ISSUE THREAD

**Issue by hms040717007** [JmoVxia/CLPlayer#12]
全屏状态下点击按钮回调执行        [self.navigationController popViewControllerAnimated:YES]; 方法返回上一界面会出现异常动画

**Comment by JmoVxia** [comment]
全屏状态点击返回按钮已经修改为直接返回小屏，小屏点击返回才调用返回按钮回调，在离开页面的时候需要销毁播放器，释放内存。

**Comment by JmoVxia** [comment]
新版本已经使用Swift重构
