### ISSUE TITLE
pod导入在图片无法加载出来，建议修改

### ISSUE THREAD

**Issue by yunjinghui123** [JmoVxia/CLPlayer#15]
这样就可以正常加载bundle图片
#pragma mark - 获取资源图片
- (UIImage *)getPictureWithName:(NSString *)name{
    id bu = [NSBundle bundleWithPath:[[NSBundle bundleForClass:[CLPlayerMaskView class]] pathForResource:@"CLPlayer" ofType:@"bundle"]];
    NSString *path = [bu pathForResource:name ofType:@"png"];
    return [[UIImage imageWithContentsOfFile:path] imageWithRenderingMode:UIImageRenderingModeAlwaysOriginal];
}

**Comment by JmoVxia** [comment]
已经测试过，没有问题

**Comment by zeroJie** [comment]
建议按上面的代码修改，要不然Swift获取的是nil
