### ISSUE TITLE
好像avi格式的播放不了，关于tableview滑动的问题

### ISSUE THREAD

**Issue by mactang** [JmoVxia/CLPlayer#17]
我想问下我把播放器放在tableview的header上，没有放在cell上，当我滑动的时候一但播放器超出屏幕，再拉回来它就会从头开始播放了，能不能不从头开始播放，而且暂停呢，需要做哪些处理，谢谢了

**Comment by JmoVxia** [comment]
经过测试，TableView的header是可以正常使用的，检查一下你是否多次传入了url导致从头开始播放，滑出暂停可以在TableView滑动代理中根据偏移量判断是暂停还是开始

**Comment by JmoVxia** [comment]
新版本已经使用Swift重构
