### ISSUE TITLE
网络不好的时候，点击播放之后整个界面卡死

### ISSUE THREAD

**Issue by xjf1990930** [JmoVxia/CLPlayer#2]
不清楚到底卡在什么地方了，就是整个tableView无法被拖动，app也没有闪退，请重现看看

**Comment by JmoVxia** [comment]
没有发现你说的问题，即时是没有网络的情况下，也没有出现卡死现象。

**Comment by JmoVxia** [comment]
增加了网络卡顿自动缓冲，缓冲好后继续播放

**Comment by JmoVxia** [comment]
以前销毁播放器的方式不对，在没有网络的时候销毁播放器会引起卡顿，现在已经解决

**Comment by xjf1990930** [comment]
谢谢，我立马去学习一下，项目中的播放器现在的释放操作确实挺麻烦。




发自网易邮箱大师
在2017年08月03日 20:26，JmoVxia 写道：

以前销毁播放器的方式不对，在没有网络的时候销毁播放器会引起卡顿，现在已经解决

**Comment by JmoVxia** [comment]
新版本已经使用Swift重构
