### ISSUE TITLE
暂停以及全屏按钮看不见的问题

### ISSUE THREAD

**Issue by flowersssss** [JmoVxia/CLPlayer#20]
暂停按钮看不见但是在那个位置点击有用 全屏则是既看不见又没用 这是创建方法
<img width="728" alt="c39c3397-61e5-458d-986b-53c2bff65fa9" src="https://user-images.githubusercontent.com/33472822/35207670-3ff10aac-ff7f-11e7-891f-4a0d1b9091a4.png">
这是效果
<img width="331" alt="4c086438-391a-483b-aa66-9561e5e352e4" src="https://user-images.githubusercontent.com/33472822/35207729-8d292ce6-ff7f-11e7-8d4c-4ce3d6afaf99.png">

**Comment by JmoVxia** [comment]
更新1.1.9版本

**Comment by JmoVxia** [comment]
新版本已经使用Swift重构
