### ISSUE TITLE
1.1.0 pod  搜索不到  是不是没有传上去

### ISSUE THREAD

**Issue by IceTears1** [JmoVxia/CLPlayer#22]
模拟器出现崩溃现象   看你推荐说让更新1.1.0  但是pod 最多只能搜索  1.0 9

**Comment by JmoVxia** [comment]
都到1.2.0版本了，清除一下你本地缓存   pod cache clean --all

**Comment by IceTears1** [comment]
找到了  这时候需要更新本地Pod的索引文件    pod setup
