### ISSUE TITLE
CPU 超过100%

### ISSUE THREAD

**Issue by zyropi** [JmoVxia/CLPlayer#24]
进入播放时, 在转子为加载出视频并点击返回后, 出现CPU超过100%, 真机会发热并在10-20分钟不等闪退..希望能对这个问题进行修复..
![image](https://user-images.githubusercontent.com/11586958/39087180-ee1f6d6c-45cf-11e8-8185-81c5b4c24795.png)
你的demo也有这个问题
![image](https://user-images.githubusercontent.com/11586958/39087202-50429d0c-45d0-11e8-9749-1b450715f039.png)

**Comment by JmoVxia** [comment]
升级新版本

**Comment by JmoVxia** [comment]
新版本已经使用Swift重构
