### ISSUE TITLE
视频暂停后锁屏手机然后解锁，视频会自动播放2秒

### ISSUE THREAD

**Issue by mulubanche** [JmoVxia/CLPlayer#27]
如题
经过测试后发现，暂停视频之后退到后台，再从后台返回的时候出现视频自动播放。
不应该播放才对

**Comment by mulubanche** [comment]
[[NSNotificationCenter defaultCenter] addObserver:self
                                                 selector:@selector(appDidEnterPlayground:)
                                                     name:UIApplicationDidBecomeActiveNotification
                                                   object:nil];
这是你监听的APP进入前台，你这样的做法我猜测应该是满足部分用户在看视频的时候从后台返回可自动继续播放，但是有部分用户不需要这个设置，可再添加一个公共属性让用户选择是否需要监听这个动作

**Comment by JmoVxia** [comment]
已经解决暂停后返回自动播放bug，并且新增了属性来控制是否需要自动播放，请更新最新版本

**Comment by JmoVxia** [comment]
新版本已经使用Swift重构
