### ISSUE TITLE
关于横竖屏切换导致黑屏

### ISSUE THREAD

**Issue by flowersssss** [JmoVxia/CLPlayer#28]
如题  我在第一次点击播放的时候切换横竖屏正常 然后第二次点击播放就会导致黑屏并且还取消不了  只能重新运行 求解决

**Comment by flowersssss** [comment]
补充一下  我在还原旋转的方法里重走了creatui  界面没问题了  但是我的顶部导航栏消失

**Comment by flowersssss** [comment]
还有 屏幕旋转通知监听了所有界面的旋转

**Comment by flowersssss** [comment]
准确的来说 当第二次点击播放 并进行横竖屏切换的时候 各种控件也会出问题 特别是退出按钮

**Comment by JmoVxia** [comment]
1.请确认你的播放器是最新版本
2.暂时只支持frame布局，检查你使用的布局方式
3.详细说明你的操作过程、当前手机系统版本、模拟器还是真机、是采用手机旋转方式全屏还是采用点击全屏按钮全屏
4.项目目前是采用监听手机的旋转，后期会考虑更好的方式来支持

**Comment by JmoVxia** [comment]
新版本已经使用Swift重构
