### ISSUE TITLE
多次 全屏播放 有问题

### ISSUE THREAD

**Issue by lafayea** [JmoVxia/CLPlayer#29]
1,我的使用场景是这样的 一个横向滑动的collectionview 里面每个item都是点击之后横屏播放视频的 多点几次 你这个转子就时不时不消失了 底下的slider也不动了 再点点又好了... 能问下啥原因么 我用的是github上最新的代码;
2,一直重复点开一个item 横屏播放 只有第一次是正常的 其他的要么是转子不转并且slider不动 要么是状态栏还是竖屏的;

**Comment by JmoVxia** [comment]
collectionview还目前没有适配，后期有空会适配

**Comment by lafayea** [comment]
找到问题了, 你这个定时器有问题, 一直没有被销毁, 我改成nstimer 在合适的时机invalidate 和 置nil就好了, 你这里的定时器是单例 还用缓存存起来了, 很容易造成循环引用

**Comment by JmoVxia** [comment]
新版本已经使用Swift重构
