### ISSUE TITLE
视频放cell里，加载数据的时候播放，会出现重用问题

### ISSUE THREAD

**Issue by gaojiewan** [JmoVxia/CLPlayer#32]
我放在tableview的cell里，由于重用会创建多个视频同时在播放，怎么解决啊？

**Comment by JmoVxia** [comment]
cell滑出的时候需要将视频播放器销毁

**Comment by gaojiewan** [comment]
还有一个问题，我是放在（tabbar的）首页的，然后跳转其他tabbar的页面时，在viewDidDisappear调用[self.playerView pausePlay];内存直接升到105%，再点回来就又正常了，怎么解决啊？

**Comment by JmoVxia** [comment]
内存请真机测试，模拟器显示不准确，视频播放都会占用内存的

**Comment by JmoVxia** [comment]
新版本已经使用Swift重构
