### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by ITLMXMF222** [JmoVxia/CLPlayer#34]
你好。请问使用代码 去设置 不让它横屏的效果  isLandscape 我看了这个参数 也设置了测试没效果

**Comment by JmoVxia** [comment]
isLandscape这个参数是你当前页面支持旋转，需要设置这个属性栏播放器能够跟随页面旋转。目前没有设计不支持横屏。

**Comment by JmoVxia** [comment]
新版本已经使用Swift重构
