### ISSUE TITLE
iOS13横屏无法隐藏状态栏了

### ISSUE THREAD

**Issue by liyinjie01** [JmoVxia/CLPlayer#37]

**Comment by isdotjim** [comment]
搭个车...
想邀请你们来w3c.group创建项目对应的小组。w3c.group是类似知识星球的社群工具，但却不是知识付费性质的创作者社区，这里有相关的文章：
http://t.cn/Ai1vLcCU
http://t.cn/Ai1vLcCG
http://t.cn/Ai1vLcCA

**Comment by JmoVxia** [comment]
状态栏交由控制器自己控制，播放器已经移除状态栏相关

**Comment by JmoVxia** [comment]
新版本已经使用Swift重构

**Comment by liyinjie01** [comment]
> 新版本已经使用Swift重构

好的，谢谢分享
