### ISSUE TITLE
缓冲条约束冲突

### ISSUE THREAD

**Issue by Jayxiang** [JmoVxia/CLPlayer#4]
约束有问题,一直报错,就是缓冲条那.你改一下吧

**Comment by JmoVxia** [comment]
系统版本是哪个？机型是哪个机型？

**Comment by Jayxiang** [comment]
10.3  7   约束的问题和这关系应该不大吧

**Comment by JmoVxia** [comment]
我真机模拟器测试都没有出现你说的问题，你确定是播放器的问题而不是你其他地方引起？

**Comment by Jayxiang** [comment]
其实也不是大问题,只是约束可能是优先级问题,会打印一些约束问题.我设置了一下优先级就好了.
[LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
	(Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
(
    "<MASLayoutConstraint:0x6100000b1640 UIView:0x7fa305f5ff50.height == 40>",
    "<MASLayoutConstraint:0x6100000b1be0 UIButton:0x7fa305f63e20.top == UIView:0x7fa305f5ff50.top + 10>",
    "<MASLayoutConstraint:0x6100000b1ca0 UIButton:0x7fa305f63e20.bottom == UIView:0x7fa305f5ff50.bottom - 10>",
    "<MASLayoutConstraint:0x6100000b1f40 UIButton:0x7fa308158850.left == UIView:0x7fa305f0e650.left + 10>",
    "<MASLayoutConstraint:0x6100000b21e0 UIButton:0x7fa305d8a820.right == UIView:0x7fa305f0e650.right - 10>",
    "<MASLayoutConstraint:0x6100000b2480 UILabel:0x7fa30815c3d0.left == UIButton:0x7fa308158850.right + 10>",
    "<MASLayoutConstraint:0x6100000b26c0 UILabel:0x7fa30815c660.right == UIButton:0x7fa305d8a820.left - 10>",
    "<MASLayoutConstraint:0x6100000b2960 UIProgressView:0x7fa30815c150.left == UILabel:0x7fa30815c3d0.right + 10>",
    "<MASLayoutConstraint:0x6100000b29c0 UIProgressView:0x7fa30815c150.right == UILabel:0x7fa30815c660.left - 10>",
    "<MASLayoutConstraint:0x6100000b1580 UIView:0x7fa305f0e650.left == CLPlayerMaskView:0x7fa305f0b550.left>",
    "<MASLayoutConstraint:0x6100000b1220 UIView:0x7fa305f0e650.right == CLPlayerMaskView:0x7fa305f0b550.right>",
    "<MASLayoutConstraint:0x6100000b2000 UIButton:0x7fa308158850.width == UIButton:0x7fa305f63e20.height>",
    "<MASLayoutConstraint:0x6100000b2300 UIButton:0x7fa305d8a820.width == UIButton:0x7fa305f63e20.height>",
    "<NSAutoresizingMaskLayoutConstraint:0x60800009ab80 CLPlayerMaskView:0x7fa305f0b550.width == 0>"
)

Will attempt to recover by breaking constraint 
<MASLayoutConstraint:0x6100000b2960 UIProgressView:0x7fa30815c150.left == UILabel:0x7fa30815c3d0.right + 10>

**Comment by JmoVxia** [comment]
已经解决，是父类控件创建的时候没有frame，在创建的时候使用自动布局添加约束引起，将约束代码放入layoutSubviews中就没有问题了

**Comment by JmoVxia** [comment]
新版本已经使用Swift重构
