### ISSUE TITLE
Demo不能运行

### ISSUE THREAD

**Issue by idlebook** [JmoVxia/CLPlayer#40]
您好，打开CLPlayerDemo.xcworkspace文件，提示error: /Users/mac/Downloads/CLPlayer-master/Pods/Target Support Files/Pods-CLPlayerDemo/Pods-CLPlayerDemo.release.xcconfig: unable to open file (in target "CLPlayerDemo" in project "CLPlayerDemo") (in target 'CLPlayerDemo')，不能运行，望解决。

**Comment by JmoVxia** [comment]
新版本已经使用Swift重构
