### ISSUE TITLE
提几个使用过程出现的问题

### ISSUE THREAD

**Issue by heshiqiuer** [JmoVxia/CLPlayer#47]
1. 视频播放到最后（进度条到底了），拖拽进度条，你会发现，视频总时长变成0了，且恢复不过来。（必现bug）
2. 视频加载过程中，播放暂停按钮不能点击，这与实际操作原则上不符合逻辑（也可能是bug吧）
3. Slider 重写后，都跑进度条外面去了（可以调整适配一下）
另外：期待作者能够把本地缓存功能弄上去，很多时候需求希望加载过后不必重新加载，当然也要提供清除缓存的功能。
加油！作者很帅！

**Comment by JmoVxia** [comment]
最新版本已经修复，本地缓存暂时没有时间做
1.支持Autolayout、UIStackView、Frame布局
2.修复Slider滑块导致UI错乱
3.修复视频播放完成后总时长变成0
