### ISSUE TITLE
在StackView中添加CLPLayer，然后点击全屏后再返回出现紊乱

### ISSUE THREAD

**Issue by GengJian** [JmoVxia/CLPlayer#48]
iOS 16

尝试重新刷新布局无效

**Comment by GengJian** [comment]
首次加载的时候小屏没问题，全屏后再点左上角返回即异常；使用Frame重新布局或者Snapkit均无效

**Comment by JmoVxia** [comment]
UIStackView、Autolayout可以描述多个控件之间的关系，还原小屏幕的时候比较麻烦，如果需要支持请自行修改源码还原小屏部分逻辑

**Comment by JmoVxia** [comment]
最新版已经支持UIStackView、Autolayout、Frame
