### ISSUE TITLE
视频开始缓冲，点击暂停按钮，暂停不能立即生效

### ISSUE THREAD

**Issue by zhewnec** [JmoVxia/CLPlayer#49]
CLPlayerView 类中的 bufferingSomeSecond 方法 的定时器没给间隔时间，会导致线程阻塞  bufferTimer = CLGCDTimer(interval: 0, delaySecs: 3.0)

**Comment by zhangxueyang** [comment]
同问，什么时候更新下呢？

**Comment by zhangxueyang** [comment]
@aizexin @JmoVxia 如果视频比较大，在缓存中，没有办法暂停视频呢？什么时候可以看下这个问题。如果需要更详细的信息，可以联系我。

**Comment by zhangxueyang** [comment]
func bufferingSomeSecond() {
        guard playerItem?.status == .readyToPlay else { return }
        guard contentView.playState != .failed else { return }

        player?.pause()
        sliderTimer?.suspend()
        bufferTimer = nil

        contentView.playState = .buffering
        bufferTimer = CLGCDTimer(interval: 0.1, delaySecs: 3.0)
        bufferTimer?.start { [weak self] _ in
            guard let playerItem = self?.playerItem else { return }
            if playerItem.isPlaybackLikelyToKeepUp {
                self?.play()
            } else {
                self?.bufferingSomeSecond()
            }
        }
    }



 bufferTimer = CLGCDTimer(interval: 0.1, delaySecs: 3.0)
这里加一个间隔就可以了
@aizexin @JmoVxia

**Comment by JmoVxia** [comment]
新版本已解决
