### ISSUE TITLE
flv后缀的url 无法播放

### ISSUE THREAD

**Issue by Zyf893549897** [JmoVxia/CLPlayer#50]

**Comment by JmoVxia** [comment]
本框架基于AVPlayer封装，支持格式：
["mqv", "pls", "aifc", "m4r", "wav", "3gp", "3g2", "flac", "avi", "m2a", "aac", "mpa", "xhe", "m3u", "mov", "aiff", "ttml", "vtt", "m4v", "amr", "caf", "m4a", "m4b", "mp4", "mp1", "m1a", "mp4", "aax", "mp2", "w64", "aa", "mp3", "itt", "au", "eac3", "webvtt", "vtt", "ac3", "m4p", "loas"]

AVURLAsset.audiovisualTypes()方法可以查询支持格式
