### ISSUE TITLE
修改一下横竖屏的问题

### ISSUE THREAD

**Issue by DongfengWang123** [JmoVxia/CLPlayer#8]
1.demo里面同一个视频,不同的单击次数,有的时候显示横屏播放,有的时候竖屏播放.
2.我是用的时候设置了isLandscape横屏播放,但是没有效果呢

**Comment by JmoVxia** [comment]
先下载1.0.6版本的demo，最近在更新中

**Comment by JmoVxia** [comment]
新版本已经使用Swift重构
